services:
  - type: web
    name: ggame-backend
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn ggame.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DATABASE_URL
        fromDatabase:
          name: ggame-db
          property: connectionString
      - key: ALLOWED_HOSTS
        value: ggame-backend.onrender.com
      - key: CORS_ALLOWED_ORIGINS
        value: https://ggame-frontend.vercel.app

databases:
  - name: ggame-db
    plan: free
